version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    entrypoint: /docker-entrypoint.sh
    command: /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf
    volumes:
      - /home/ubuntu/mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"       # Expose MQTT port directly on host
      - "9001:9001"       # If websockets MQTT is used and exposed
    networks:
      - traefik
    labels:
      traefik.enable: "true"

      # Web UI over HTTPS via Traefik (if you have a web interface for Mosquitto)
      traefik.http.routers.mosquitto.rule: Host(`mqtt.stl1.co.kr`)
      traefik.http.routers.mosquitto.entrypoints: websecure
      traefik.http.routers.mosquitto.tls.certresolver: resolver
      traefik.http.services.mosquitto.loadbalancer.server.port: 9001
      traefik.http.services.mosquitto.loadbalancer.server.scheme: http

      # Removed TCP MQTT Traefik labels because Traefik does not have MQTT entrypoint configured

volumes:
  mosquitto_data:
  mosquitto_log:

networks:
  traefik:
    external: true
